"""changes in relationships 3

Revision ID: 5ed67e21bb8f
Revises: a1ce09c506c8
Create Date: 2023-12-05 12:13:21.504956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ed67e21bb8f"
down_revision: Union[str, None] = "a1ce09c506c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
